name: 'Create release from NPM workspaces changelogs'
description: 'Automatically create draft releases depending on the CHANGELOG.md files of each npm workspace of the repo.'
inputs:
  github-auth-token:  
    description: 'The GitHub auth token'
    required: true
  package-name-suffix-to-ignore:
    description: 'A suffix in the nmp packages names that should be ignored for release names'
    required: false
outputs:
  response: # id of output
    description: 'The result of the operation'
runs:
  using: 'node12'
  main: 'dist/index.js'